version: '3.6'

services:
  etcd-01:
    image: etcd-01:v1
    build:
      context: etcd
    hostname: etcd-01
    volumes:
      - ./etcd/config/etcd-01.yaml:/var/lib/etcd/etcd.yaml:ro
      - etcd-01-datadir:/var/lib/etcd:rw
    ports:
      - 2371:2379
      - 2381:2380
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.10'
  etcd-02:
    image: etcd-02:v1
    build:
      context: etcd
    hostname: etcd-02
    volumes:
      - ./etcd/config/etcd-02.yaml:/var/lib/etcd/etcd.yaml:ro
      - etcd-02-datadir:/var/lib/etcd:rw
    ports:
      - 2372:2379
      - 2382:2380
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.11'
  etcd-03:
      image: etcd-03:v1
      build:
        context: etcd
      hostname: etcd-03
      volumes:
        - ./etcd/config/etcd-03.yaml:/var/lib/etcd/etcd.yaml:ro
        - etcd-03-datadir:/var/lib/etcd:rw
      ports:
        - 2373:2379
        - 2383:2380
      networks:
        patroni-cluster:
          ipv4_address: '10.10.0.12'

  patroni-01:
    image: patroni-01:v1
    build:
      context: patroni
      args:
        - OS_PATRONI_USER_PASS=${OS_PATRONI_USER_PASS}
    hostname: patroni-01
    volumes:
      - ./patroni/config/patroni-01.yaml:/home/patroni/patroni.yaml:ro
      - ./patroni/config/postgresql.conf:/home/patroni/postgresql.conf:ro
      - patroni-01-datadir:/var/lib/patroni/data:rw
      - patroni-01-logdir:/var/lib/patroni/log:rw
    ports:
      - 5432:5432
      - 8008:8008
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.20'
    depends_on:
      - etcd-01
      - etcd-02
      - etcd-03
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "/var/lib/patroni/data/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  patroni-02:
    image: patroni-02:v1
    build:
      context: patroni
      args:
        - OS_PATRONI_USER_PASS=${OS_PATRONI_USER_PASS}
    hostname: patroni-02
    volumes:
      - ./patroni/config/patroni-02.yaml:/home/patroni/patroni.yaml:ro
      - ./patroni/config/postgresql.conf:/home/patroni/postgresql.conf:ro
      - patroni-02-datadir:/var/lib/patroni/data:rw
      - patroni-02-logdir:/var/lib/patroni/log:rw
    ports:
      - 5433:5432
      - 8009:8008
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.21'
    depends_on:
      - etcd-01
      - etcd-02
      - etcd-03
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "/var/lib/patroni/data/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  pgbadger:
    image: pgbadger:v1
    build:
      context: pgbadger
    hostname: pgbadger
    ports:
      - 8081:80
    networks:
      - patroni-cluster
    volumes:
      - pgbadger-datadir:/var/lib/pgbadger/data:rw
      - patroni-01-logdir:/var/lib/patroni-01/log:ro
      - patroni-02-logdir:/var/lib/patroni-02/log:ro
    depends_on:
      - patroni-01
      - patroni-02

  barman:
    image: barman:v1
    build:
      context: barman
      args:
        - OS_BARMAN_USER_PASS=${OS_BARMAN_USER_PASS}
    environment:
      - OS_PATRONI_USER_PASS=${OS_PATRONI_USER_PASS}
    hostname: barman
    networks:
      - patroni-cluster
    volumes:
      - barman-datadir:/var/lib/barman/data:rw
    depends_on:
      - patroni-01
      - patroni-02

networks:
  patroni-cluster:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  etcd-01-datadir: {}
  etcd-02-datadir: {}
  etcd-03-datadir: {}
  patroni-01-datadir: {}
  patroni-02-datadir: {}
  patroni-01-logdir: {}
  patroni-02-logdir: {}
  pgbadger-datadir: {}
  barman-datadir: {}
