version: '3.6'

services:
  etcd-01:
    image: etcd-01:v1
    build:
      context: etcd
    volumes:
      - ./etcd/config/etcd-01.yaml:/var/lib/etcd/etcd.yaml:ro
      - etcd-01-datadir:/var/lib/etcd/:rw
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.10'

  patroni-01:
    image: patroni-01:v1
    build:
      context: patroni
    volumes:
      - ./patroni/config/patroni-01.yaml:/home/patroni/patroni.yaml:ro
      - patroni-01-datadir:/var/lib/pgsql/13/data/:rw
    ports:
      - 5432:5432
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.20'
    depends_on:
      - etcd-01

  patroni-02:
    image: patroni-02:v1
    build:
      context: patroni
    volumes:
      - ./patroni/config/patroni-02.yaml:/home/patroni/patroni.yaml:ro
      - patroni-02-datadir:/var/lib/pgsql/13/data/:rw
    ports:
      - 5433:5432
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.21'
    depends_on:
      - etcd-01

  haproxy:
    image: haproxy:v1
    build:
      context: HAProxy
    ports:
      - 5000:5000
      - 7000:7000
    networks:
      patroni-cluster:
        ipv4_address: '10.10.0.30'

networks:
  patroni-cluster:
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24

volumes:
  etcd-01-datadir: {}
  patroni-01-datadir: {}
  patroni-02-datadir: {}
